import type { FaqItem, OutlineStylePreset, PracticePaperOption, ScenarioRecommendation } from "@/types/site";

export const exampleTexts = [
  "今天也要好好写字",
  "手账标题练习",
  "春日学习清单",
  "数学笔记重点",
  "晚安日记计划",
];

export const practicePaperOptions: PracticePaperOption[] = [
  {
    id: "grid",
    label: "方格纸",
    description: "适合找重心、控字宽，第一次练空心字会更稳。",
  },
  {
    id: "dot",
    label: "点点纸",
    description: "适合已经会写基础结构，想练更轻盈的排版节奏。",
  },
];

export const outlineStyles: OutlineStylePreset[] = [
  {
    id: "soft-candy",
    name: "软糖圆圆",
    shortDescription: "圆润、软糯、很适合手账标题和日记小版头。",
    tone: "轻轻鼓起来的圆角线条，像用牛奶笔包了一圈。",
    previewLabel: "圆润可爱风",
    previewBadge: "新手友好",
    bestFor: "手账标题、日记页签、小栏目名",
    difficulty: "容易上手",
    recommendedLength: "6 到 12 字最舒服",
    guideSlug: "journal-outline",
    strokeWidth: 14,
    innerStrokeWidth: 7,
    letterSpacing: 12,
    fontWeight: 500,
    capStyle: "round",
    cornerStyle: "round",
    accentColor: "#f49ab2",
    outlineColor: "#dd6c8a",
    softFillColor: "#fff7fa",
    supportColor: "#87c8b5",
    background: {
      from: "#fff8fb",
      via: "#fffef6",
      to: "#eefcf7",
      notebook: "#f8dfe9",
      tape: "#ffd8a8",
    },
    exportCaption: "软糖圆圆更适合短标题，先写小一圈，再慢慢包大。",
    hintSentence: "先写得小一点，圆角留空会更可爱。",
    scenarioTags: ["手账", "日记", "可爱标题"],
    commonMistakes: [
      "每一笔都包得太满，转角没有留空气感。",
      "横画和竖画粗细不一，整行看起来会忽胖忽瘦。",
      "把字写得太大，外扩后就没有边距了。",
    ],
    teachingSteps: [
      {
        shortLabel: "定位",
        title: "先用轻笔写一个小一圈的原字",
        description: "把字先写在格子的中间，宁可小一点，也别一开始就顶满。",
        coaching: "想象最后还要在外面再包一层，所以先给轮廓留房间。",
        emphasis: "圆润风最怕起笔就写满。",
      },
      {
        shortLabel: "外包",
        title: "沿笔画外侧慢慢包出圆圆的边",
        description: "不要死贴原字，用一条平稳的距离把外轮廓绕出来。",
        coaching: "转角往外拱一点，会比硬折角更软糯。",
        emphasis: "线和原字之间的距离尽量一致。",
      },
      {
        shortLabel: "统一",
        title: "把整字的线宽统一成同一种厚度",
        description: "如果某一笔包得太厚，就轻轻往里收；太薄就补一点点。",
        coaching: "先看横竖主笔，再看小撇小点，不要一上来盯细节。",
        emphasis: "先统一粗细，再修细节。",
      },
      {
        shortLabel: "收尾",
        title: "把连接处修顺，让圆角有呼吸感",
        description: "最后把接缝和小尖角磨圆，留出干净的小空白。",
        coaching: "圆角不是全都画成半圆，而是看上去柔和、不扎手。",
        emphasis: "收尾时尽量少补线，多修顺。",
      },
    ],
    penTips: {
      startingMethod: "先写中心字，再向外包轮廓。",
      crowdedParts: "口字旁、心字底、女字旁容易挤在一起。",
      penAdvice: "0.5 中性笔或细头马克笔都适合，太粗会失去软感。",
      beginnerMistake: "一味追求圆，结果把结构写散了。",
    },
  },
  {
    id: "neat-title",
    name: "工整标题",
    shortDescription: "规整、稳当，最适合课堂标题和作业排版。",
    tone: "边线笔直、重心清楚，看起来像认真整理过的课本标题。",
    previewLabel: "规范标题风",
    previewBadge: "课堂常用",
    bestFor: "课堂标题、作业版头、工整笔记",
    difficulty: "中等偏易",
    recommendedLength: "8 到 16 字很耐看",
    guideSlug: "title-outline",
    strokeWidth: 14,
    innerStrokeWidth: 6,
    letterSpacing: 10,
    fontWeight: 520,
    capStyle: "square",
    cornerStyle: "square",
    accentColor: "#5f8bd7",
    outlineColor: "#3f6ebd",
    softFillColor: "#f7fbff",
    supportColor: "#8bbfae",
    background: {
      from: "#f7fbff",
      via: "#fefcf7",
      to: "#f3fff9",
      notebook: "#d7e5fb",
      tape: "#c3efd8",
    },
    exportCaption: "工整标题适合抄到课堂笔记里，外轮廓要像搭好框架一样稳。",
    hintSentence: "先看整行基线，再看每个字的上下左右边距。",
    scenarioTags: ["课堂", "作业", "工整笔记"],
    commonMistakes: [
      "只顾单字好看，整行高低不齐。",
      "直角没有对准，导致字边线东倒西歪。",
      "上下结构的字写太满，空心部分被挤薄了。",
    ],
    teachingSteps: [
      {
        shortLabel: "基线",
        title: "先找整行的基线和字宽",
        description: "先决定这行标题写多宽、多高，再把每个字轻轻摆进去。",
        coaching: "工整感来自整体对齐，不是某一个字特别用力。",
        emphasis: "先排整行，再画单字。",
      },
      {
        shortLabel: "框出",
        title: "沿主笔画外侧包出清楚的方形边",
        description: "横要平、竖要直，转角可以利落一点，不需要太圆。",
        coaching: "遇到左右结构时，先框大结构，再补小部件。",
        emphasis: "优先看垂直线是否稳。",
      },
      {
        shortLabel: "校准",
        title: "统一线宽和边距，让每一笔都像同一把尺子量出来的",
        description: "检查横画、竖画和包围框之间的距离，不一致就调整。",
        coaching: "空心字不是越粗越好，太厚会变笨重。",
        emphasis: "留白要均匀，特别是中宫位置。",
      },
      {
        shortLabel: "收齐",
        title: "修齐边角，让整行标题有课本页眉的稳定感",
        description: "最后退远一点看整体，把跳出来的边线修回队伍里。",
        coaching: "如果你一眼先看见某个字，通常就是它跑偏了。",
        emphasis: "整体平衡比单字花哨更重要。",
      },
    ],
    penTips: {
      startingMethod: "先定整行框架，再写字骨架，最后再包轮廓。",
      crowdedParts: "上下结构的字、带包围框的字最容易上紧下松。",
      penAdvice: "0.5 中性笔或针管笔更稳，适合追求干净边线。",
      beginnerMistake: "只修局部，忽略整行对齐。",
    },
  },
  {
    id: "journal-decor",
    name: "手账花边",
    shortDescription: "在基础空心字外多一点装饰边，适合便签、栏目名和贴纸感标题。",
    tone: "有一点小花边和空气感，像手账页边的可爱标签。",
    previewLabel: "手账装饰风",
    previewBadge: "装饰感",
    bestFor: "便签标题、清单页签、手账分区",
    difficulty: "中等",
    recommendedLength: "4 到 10 字最灵动",
    guideSlug: "journal-outline",
    strokeWidth: 15,
    innerStrokeWidth: 5,
    letterSpacing: 13,
    fontWeight: 520,
    capStyle: "round",
    cornerStyle: "round",
    accentColor: "#f29d4b",
    outlineColor: "#d07a1e",
    softFillColor: "#fffaf2",
    supportColor: "#78b7d0",
    background: {
      from: "#fffdf7",
      via: "#fff7ef",
      to: "#f1fbff",
      notebook: "#f4e1c6",
      tape: "#ffe4ec",
    },
    exportCaption: "手账花边适合短短的栏目标，最后多加一点轻装饰就会很出彩。",
    hintSentence: "先把空心字写稳，再加小花边，不然容易乱。",
    scenarioTags: ["便签", "手账栏目", "贴纸感标题"],
    commonMistakes: [
      "装饰比字本身还抢眼，导致标题看不清。",
      "边线包得不稳，就开始加点点和小尾巴。",
      "每一笔都想加装饰，结果视觉很吵。",
    ],
    teachingSteps: [
      {
        shortLabel: "骨架",
        title: "先写出稳稳的基础空心字骨架",
        description: "先把字的轮廓写好，确认结构不歪，再考虑装饰。",
        coaching: "把它当成一张标签底稿，而不是一开始就画贴纸。",
        emphasis: "没有稳骨架，就不要先加花边。",
      },
      {
        shortLabel: "外扩",
        title: "包轮廓时留一点外圈空气",
        description: "和圆润风相比，这一款可以稍微更松一点，让装饰有落点。",
        coaching: "每个字之间也要留空，不然花边会互相撞。",
        emphasis: "为装饰预留边距。",
      },
      {
        shortLabel: "点缀",
        title: "在转角或尾部加一两个轻装饰",
        description: "只挑重点位置加小点、短尾巴或波浪边，不要全字铺满。",
        coaching: "一字一重点，数量少反而更高级。",
        emphasis: "装饰是陪衬，不是主角。",
      },
      {
        shortLabel: "平衡",
        title: "最后把整行的轻重重新拉平",
        description: "看一眼哪些字装饰过多，把最显眼的地方收一收。",
        coaching: "可爱感来自轻盈，不来自堆满细节。",
        emphasis: "宁可少一点，也别乱一点。",
      },
    ],
    penTips: {
      startingMethod: "先写空心字主体，装饰留到最后 20%。",
      crowdedParts: "带口、日、田之类的小空间最容易被装饰占满。",
      penAdvice: "主字用 0.5 中性笔，装饰可换彩色细笔点一下。",
      beginnerMistake: "装饰太平均，反而没有节奏。",
    },
  },
  {
    id: "chalk-board",
    name: "黑板报体",
    shortDescription: "描边更醒目，字块更大，适合板报、手抄报和远看也清楚的大标题。",
    tone: "像粉笔描边的大标题，存在感强，但结构仍要干净。",
    previewLabel: "黑板报风",
    previewBadge: "远看醒目",
    bestFor: "黑板报、手抄报、板书大标题",
    difficulty: "中等",
    recommendedLength: "4 到 12 字最有气势",
    guideSlug: "blackboard-outline",
    strokeWidth: 18,
    innerStrokeWidth: 8,
    letterSpacing: 14,
    fontWeight: 600,
    capStyle: "square",
    cornerStyle: "square",
    accentColor: "#5e7d64",
    outlineColor: "#274b33",
    softFillColor: "#f5fff6",
    supportColor: "#e8c36a",
    background: {
      from: "#f7fff8",
      via: "#eff8f1",
      to: "#fbf6e6",
      notebook: "#cfe6d1",
      tape: "#f5d98f",
    },
    exportCaption: "黑板报体重点是远看清楚，外轮廓要大胆，但内部别堵死。",
    hintSentence: "字大时先看大结构，不要一开始钻进小笔画里。",
    scenarioTags: ["黑板报", "手抄报", "大标题"],
    commonMistakes: [
      "描边太厚，内部留白挤没了。",
      "大标题写得很大，但每个字宽度不统一。",
      "只顾粗描边，忽略了字的重心和倾斜。",
    ],
    teachingSteps: [
      {
        shortLabel: "定块",
        title: "先把字当成一个个大块面摆好",
        description: "大标题先看字块大小、字距和整行气势，别急着画细节。",
        coaching: "黑板报字要先站稳，再谈气势。",
        emphasis: "先看整体比例。",
      },
      {
        shortLabel: "大包",
        title: "用更厚的边线包出醒目的外轮廓",
        description: "这一步可以比平时更大胆，但厚度要整字统一。",
        coaching: "包得厚，不等于每个缝都堵满。",
        emphasis: "厚描边也要留出中宫。",
      },
      {
        shortLabel: "腾空",
        title: "把内部空白挖出来，让字远看也清楚",
        description: "尤其是口、日、月、田这些结构，内部空白一定要够大。",
        coaching: "远看识别度，靠的是清楚的留白。",
        emphasis: "别让粗描边吃掉字的呼吸感。",
      },
      {
        shortLabel: "提亮",
        title: "最后补一点强调边，让标题更有板报感",
        description: "可以在一侧加轻微亮边或小阴影，但只做辅助，不抢主体。",
        coaching: "提亮只是一层味道，不是再包一遍大边。",
        emphasis: "醒目来自结构，不来自堆效果。",
      },
    ],
    penTips: {
      startingMethod: "先定整行占位，再写大骨架，最后厚描边。",
      crowdedParts: "包围结构和密笔画字最容易一粗就糊。",
      penAdvice: "适合粗一点的马克笔或粉笔感笔刷，但收尾用细笔修边更稳。",
      beginnerMistake: "一味加粗，忘了内部要透气。",
    },
  },
  {
    id: "light-modern",
    name: "轻简现代",
    shortDescription: "线条更轻、留白更多，适合清爽笔记和极简风页面。",
    tone: "像干净的纸面边框，轻轻一圈，但不软塌。",
    previewLabel: "简洁现代风",
    previewBadge: "清爽留白",
    bestFor: "清爽笔记、学习计划、简约海报",
    difficulty: "中等偏上",
    recommendedLength: "8 到 18 字都很耐看",
    guideSlug: "outline-basics",
    strokeWidth: 11,
    innerStrokeWidth: 4,
    letterSpacing: 16,
    fontWeight: 460,
    capStyle: "round",
    cornerStyle: "square",
    accentColor: "#9aade2",
    outlineColor: "#7684b6",
    softFillColor: "#fbfcff",
    supportColor: "#9ab7c8",
    background: {
      from: "#fdfdff",
      via: "#f7f8fc",
      to: "#f7fbfa",
      notebook: "#d7deef",
      tape: "#dbeee7",
    },
    exportCaption: "轻简现代更适合干净版面，边线要轻，字与字之间要会呼吸。",
    hintSentence: "不要急着加粗，现代感往往来自节制。",
    scenarioTags: ["学习计划", "清爽笔记", "简约海报"],
    commonMistakes: [
      "为了清爽把线写得太细，结果远看不清。",
      "字距没有拉开，整行看起来还是挤。",
      "用太多小装饰，破坏了现代感。",
    ],
    teachingSteps: [
      {
        shortLabel: "收小",
        title: "先把字写得收一点，给留白让路",
        description: "现代风最重要的是轻和净，所以起稿先别占满格子。",
        coaching: "写字时先想周围的空白，而不是先想边线多厚。",
        emphasis: "空白是这款风格的一部分。",
      },
      {
        shortLabel: "细包",
        title: "用更细的距离包出清楚边线",
        description: "轮廓不用太厚，但要连续、干净，尤其注意直线段。",
        coaching: "越轻的轮廓，越需要边线稳定。",
        emphasis: "薄描边更考验稳定度。",
      },
      {
        shortLabel: "疏开",
        title: "把字距和内部留白一起拉开",
        description: "轻简风不是只有细线，还要让整行显得舒展。",
        coaching: "行气松一点，画面才会显得清爽。",
        emphasis: "字与字之间也要会呼吸。",
      },
      {
        shortLabel: "净面",
        title: "最后收掉多余线头，让画面保持简洁",
        description: "看到不必要的小尖角、小补线，就把它们清掉。",
        coaching: "现代感靠克制，不靠堆细节。",
        emphasis: "宁可干净一点，也别热闹一点。",
      },
    ],
    penTips: {
      startingMethod: "先定字距，再包细轮廓，最后统一线感。",
      crowdedParts: "密集偏旁和上下结构字会让轻线显得不稳。",
      penAdvice: "针管笔、细中性笔更合适，避免太粗的出墨。",
      beginnerMistake: "把轻简写成没精神，通常是边线不稳或留白不够。",
    },
  },
];

export const scenarioRecommendations: ScenarioRecommendation[] = [
  {
    id: "title",
    title: "课堂标题",
    description: "适合写在页眉、章节开头或老师要求工整的作业版头。",
    recommendation: "选工整标题，字距稳、重心正，抄在本子上最不容易翻车。",
    styleId: "neat-title",
  },
  {
    id: "journal",
    title: "手账栏目",
    description: "适合每天的小栏目名、月计划页签、心情记录标题。",
    recommendation: "软糖圆圆和手账花边都适合，前者更稳，后者更活泼。",
    styleId: "soft-candy",
  },
  {
    id: "notes",
    title: "工整笔记",
    description: "想让笔记显得清爽，但又不想太花哨的时候。",
    recommendation: "轻简现代最适合，留白干净，配直尺和淡色荧光笔也很好看。",
    styleId: "light-modern",
  },
  {
    id: "blackboard",
    title: "黑板报与手抄报",
    description: "需要远看醒目，标题大、字块感强的时候。",
    recommendation: "黑板报体最稳，先把字块排开，再加厚轮廓就很出效果。",
    styleId: "chalk-board",
  },
  {
    id: "decor",
    title: "日记装饰字",
    description: "想让整页多一点可爱感和手作感，但不想太幼稚。",
    recommendation: "手账花边更适合短标题，装饰只点到为止会更高级。",
    styleId: "journal-decor",
  },
];

export const faqItems: FaqItem[] = [
  {
    question: "什么是空心字？",
    answer: "空心字就是先保留文字结构，再把笔画画成轮廓边，让字的中间留白。它适合做标题、手账、板书和需要醒目但不沉重的字。",
  },
  {
    question: "中文空心字为什么要先写骨架？",
    answer: "因为中文笔画多、结构复杂，直接包边很容易歪。先轻轻写一个骨架字，能帮你抓住重心、部件关系和字距，再外扩就会稳很多。",
  },
  {
    question: "怎样避免空心字越写越挤？",
    answer: "起稿时就把字写小一圈，给外轮廓留出空间；包边时保持距离一致，尤其要照顾口、日、月、田这类内部容易被吃掉的结构。",
  },
  {
    question: "新手最适合从哪一种风格开始？",
    answer: "如果你平时写字比较工整，先练工整标题；如果更喜欢手账和可爱风，从软糖圆圆开始也很合适。两者都比装饰型风格更容易稳定。",
  },
  {
    question: "为什么有些转角不能贴得太满？",
    answer: "空心字好看靠的是线条和留白一起工作。转角如果挤满，字会显得闷又笨重；稍微留一点空气，轮廓才会轻盈、耐看。",
  },
];
